### PR TITLE
Add extra_settings and AsioSettings

### PR DESCRIPTION
**Pull request by mgeier**
WARNING: this is untested!

See #4.

### CODE REVIEW

**Comment by mgeier** [comment]
As long as there are no docs available, this is one way to use it:

```python
import sounddevice as sd
extra = sd.AsioSettings(channel_selectors=[9, 10])
sd.play(mydata, fs, extra_settings=extra)
```

**Comment by raecke** [comment]
This was unexpectedly fast.

I tested recording and playing with an arbitrary channel selection with a 10 channel soundcard. It works perfectly.

**Comment by mgeier** [comment]
Thanks for testing!

Can you please do further tests:

* [ ] Using a non-existing channel number in `channel_selectors` should raise an error. Can you please post the error here? Please also try `0` and a negative number.

* [ ] If `len(channel_selectors) != channels` the library might crash. Can you please try this with `channel_selectors` longer and shorter than the number of available hardware channels? Can you please artificially reduce the number of channels with `channels=N` and then try it with a length between `N` and the actual number of hardware channels?

* [ ] What happens if the length is zero?

**Comment by raecke** [comment]
1.   If any channel number is invalid (`0` is a valid channel number.), I get the error message :    
    `PortAudioError: Error opening InputStream: Invalid number of channels`.

2.  If the length of the `channel_selectors` list greater than the `channels` parameter, only the first part of the list is used. if the length of the `channel_selectors` list is smaller, I get the error :     
    `PortAudioError: Error opening InputStream: Invalid number of channels`.

3. If the length of the `channel_selectors` list zero. I get the error message:  
    `PortAudioError: Error opening InputStream: Invalid number of channels`.

**Comment by mgeier** [comment]
Thanks for testing!

All those sound like reasonable error behaviors, right?

Are the channel numbers zero-based?

Anything else I should add to the docs?

**Comment by raecke** [comment]
- The first error message is not ideal because you would think the length of the `channel_selectors` list is wrong, but it is the content that is wrong. But as this is the error that portaudio reports, I would be reluctant to change this.
- The channel numbers are zero based.
- I think the documentation needs:
 - The example above.
 - The remark that the channel numbers are zero based.
 - The remark that the information about the number of channels still needs to be provided and has to be equal to `len(channel_selectors)`.

**Comment by mgeier** [comment]
Thanks! I'll make the suggested changes next week.

**Comment by mgeier** [comment]
I've added the suggested information to the docs: http://python-sounddevice.readthedocs.io/en/latest/#sounddevice.AsioSettings

If there is something unclear/missing, or if the examples don't work as shown, please make a PR with the corrections!

**Pull request merged**
