### PR TITLE
Add PaWasapi_UpdateDeviceList to cdef

### LINKED ISSUE #484: Please add PaWasapi_UpdateDeviceList
Please for windows make a distribution with PaWasapi_UpdateDeviceList enabled, its possible?
Thanks

### PR DESCRIPTION
**Pull request by mgeier**
Closes #484.

### CODE REVIEW

**Comment by Swiftgti** [comment]
Hi, I modified sounddevice and build a new FFI with function PaWasapi_UpdateDeviceList , BUT PortAudio can't open new streams for new devices detected, for that must be used the UpdateAvailableDeviceList that is in the fork of jitsi.
It's a PortAudio fork powered with necessary features like the hotplug capabilities.
There is any way to use PortAudio of jitsi ? or support it like an option? or move the project to use that fork?
Have a nice day.

**Comment by mgeier** [comment]
See my answer at https://github.com/spatialaudio/python-sounddevice/issues/484#issuecomment-1703176427

**Comment by tihoangyeudau** [comment]
how to use this Merge? for example, if I change output sound device, can this make it's loopback list update forward it realtime?

**Comment by mgeier** [comment]
I have never used this myself, so I don't really know, but you can try something like this:

```python
import sounddevice as sd

sd._lib.PaWasapi_UpdateDeviceList()
```

**Comment by tihoangyeudau** [comment]
> I have never used this myself, so I don't really know, but you can try something like this:
> 
> ```python
> import sounddevice as sd
> 
> sd._lib.PaWasapi_UpdateDeviceList()
> ```

thank you so much, I will try it and confirm if it would work

**Pull request merged**
